### ISSUE TITLE
How to retroject to 'epsg:28992' instead of WSG84

### ISSUE THREAD

**Issue by MaartenKool** [carlosg-m/goose#1]
I am using the code to create altitude contours in NL. I would like to reproject to 'epsg:28992'. I can't seem to find where you reproject to WGS84 (so I would be able to insert a different reprojection there).  I am not the greatest python programmer so may misunderstand your code.

Thanks,
Maarten Kool

**Comment by carlosg-m** [comment]
Hi @MaartenKool

When you call the method `get_elevation` you should have a parameter called `input_crs` that defines the input coordinate reference system and is by default 'epsg:4326' or WGS84 as you said. If your input points are in another projected coordinate system, you should be able to change this parameter to 'epsg:28992'. From here forward the process remains the same, however the parameters `lat_col` and `lon_col` will represent the y and x coordinates of your projection. Note that projections are handled internally by `pyproj`.

Let me know if that worked out.
Carlos Gameiro

```
 def get_elevation(self, df, lat_col, lon_col, input_crs='epsg:4326'):
        """
        User interface. Allows to retrieve elevation for a dataframe that contains WGS84 coordinates.
        The elevation column is appended to the input dataframe.
        All original columns of the dataframe are also returned (e.g. keys).
        Null input values values are supported and kept. 
        Elevation values for points that are out-of-bounds are treated as null.
        The raster uses a mask, a large negative value, around water bodies and the ocean.
        
        df: Pandas dataframe with coordinates and miscellaneous columns.
        lat_col: name of column that contains latitude.
        lon_col: name of columns that contains longitude.
        input_crs: input CRS, by default is WGS84 (EPSG:4326).
        """
        
        df = self._generate_temp_key(df)
        df = df.merge(self._get_df_elevation(df, lat_col, lon_col, input_crs), 'left', self.col_temp_key)
        df = df.drop(self.col_temp_key, axis=1)
        
        return df
```

**Comment by MaartenKool** [comment]
Hi Carlos,

Thanks for the quick reply. My error was in the prior step: test_points = get_test_points(). Obviously lat/lon (actually Y/X) need to be declared in meters and not degrees :-). Your code  does help me generating _free_ elevation contours.

Maarten

**Comment by carlosg-m** [comment]
> lat/lon (actually Y/X) need to be declared in meters and not degrees

Yes, very important detail.
